name: Docker build and push

on:
  pull_request:
    paths:
      - management_api_app/**/*
  push:
    branches: [ develop, main ]
    paths:
      - management_api_app/**/*
  workflow_dispatch:

jobs:
  docker_build:
    name: Build & publish Management API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.docker_registry_server }}
          username: ${{ secrets.docker_registry_username }}
          password: ${{ secrets.docker_registry_password }}

      - name: Build & publish image
        env:
          DOCKER_BUILDKIT: 1
          REPOSITORY_NAME: ${{ secrets.docker_registry_server }}/microsoft/azuretre/management-api
        run: |
          echo $GITHUB_REF
          if [ $GITHUB_EVENT_NAME == 'push' ] && [ $GITHUB_REF == 'refs/heads/develop' ]; then
            TAG='develop-latest'
          elif [ $GITHUB_EVENT_NAME == 'push' ] && [ $GITHUB_REF == 'refs/heads/main' ]; then
            TAG='main-latest'
          else
            TAG=$GITHUB_SHA
          fi

          docker build -t ${{ env.REPOSITORY_NAME}}:$TAG management_api_app/
          docker push ${{ env.REPOSITORY_NAME}}:$TAG
